### ISSUE TITLE
Release under MIT License?

### ISSUE THREAD

**Issue by LucasCioffi** [cranieri/meetup_client#2]
Hello @cranieri you've done good work with this gem.  I see that it's copyrighted.  Will you release this under an MIT license so that people can use it on their projects?

**Comment by LucasCioffi** [comment]
Hello, @cranieri did you choose a license for this gem?

**Comment by LucasCioffi** [comment]
Hello, @cranieri is this gem open source?  Thank you!

**Comment by specious** [comment]
MIT license was added in 13d11533f854f68dcfb493879c858fd22fa92700.
