### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by appahub** [cranieri/meetup_client#3]
I got this error when call open_events by parameter like this

```
:lat => 40.745341,
:lon => -73.93907,
:radius => 1,
:text_format => "plain",
:fields => "group_photo"
```

and error 

```
JSON::ParserError: 399: unexpected token at '{"utc_offset":-14400000,"venue":{"zip":"11101","country":"us","city":"Long Island City","address_1":"2428 Jackson Ave.","name":"Brooks 1890","lon":-73.94411,"id":15735482,"state":"NY","lat":40.746124,"repinned":false},"headcount":0,"distance":0.26988518238067627,"visibility":"public","waitlist_count":0,"created":1433282427000,"maybe_rsvp_count":0,"description":"&gt;&gt;&gt; Manhattan, Brooklyn y Queens &lt;&lt;&lt;\n\nPara noches de buenas conversaciónes con&nbsp;hispanohablantes de varios niveles viniendo de la España, Latino America y los Estados Unidos.\n\nEste lugar es muy fácil de alcanzar. Cerca de la parada de Court Square de los trenes E, M, G y el #7 and B62 bus stop coming from Williamsburg.\n\nTodos los demás de otros partes (New Jersey, Long Island, etc.) también están invitados y nos esperaremos allí.\n\nNo hay Curfew para este Meetup. Cualquiera puede venir y quedarse hasta whenever. Aunque, la mayoría va a estar allí temprano. &nbsp;Pero apurate! el *Happy Hour* se termina a las&nbsp;7. &nbsp;\n\nThe&nbsp;Cost&nbsp;of this event is a&nbsp;1 Drink&nbsp;Minimum.----------------http:\/\/goo.gl\/maps\/VXh5k &nbsp;(corner of Court Sq &amp; Jackson Ave)AT COURT SQUARE SUBWAY STATION","how_to_find_us":">>> Ask the Wait Staff to direct you <<>> Ask the Wait Staff to direct you <<:40.745341}}
```

**Comment by cranieri** [comment]
Hi! Thank you for reporting the issue. I will take a look at it and let you know

**Comment by ronshoshani** [comment]
I have the same issue.
The code that seems to mess up with the JSON structure is this:
https://github.com/cranieri/meetup_client/blob/master/lib/api_callers/json_request.rb#L12

Can you please explain the purpose of the response cleaning?

**Comment by ronshoshani** [comment]
Btw, I have the JSON body which causes the parsing error. I can't upload it here, so let me know if you'd like me to send it via other means.

**Comment by cranieri** [comment]
Hi guys, I didn't manage to replicate the issue. I receive events when calling open_events with the following json:

```
{
        :lat => 40.745341,
        :lon => -73.93907,
        :radius => 1,
        :text_format => "plain",
        :fields => "group_photo"
}
```

Which is the one appahub reported.

@appahub is the issue still happening to you?
@ronshoshani, could you please send me the payload that was causing the issue to you? Please send it to the following email address: co.ranieri@gmail.com

Thanks a lot

**Comment by cranieri** [comment]
@appahub & @ronshoshani please upgrade your gem version to 0.0.8 and let me know if you still see the issue.

**Comment by ronshoshani** [comment]
I didn't test the new version yet, but I see you removed the line I mentioned about so it should now work.

**Comment by cranieri** [comment]
yes @ronshoshani , I did that cause honestly I don't remember (last time I touched the code was 2 years ago :) ) why that sanitisation method was there and was causing some problem.
I consider the issue closed then
